taps:
  # - nektos/tap
  - aws/tap
  - heroku/brew
  - homebrew/cask-fonts

brews:
  - vegeta
  - tfsec
  - doctl
  - flyctl
  - derailed/k9s/k9s
  - mkcert
  - nss
  - openssh
  - hyperfine
  - kafkacat
  - pre-commit
  - tsung
  - wrk
  - fswatch
  - protobuf
  # - tilt-dev/tap/tilt
  - jq
  - nmap
  - tmate
  - dive
  # - rbq/homebrew-kubeflow/kfctl
  - packer
  - openshift-cli
  - drone-cli
  - git-lfs
  - aws-sam-cli
  - awscli
  - azure-cli
  # - nektos/tap/act
  - git-flow
  - ack
  - imagemagick
  - leiningen
  - github/gh/gh
  - spaceman-diff
  - jp2a
  - openssl
  - fop
  - libyaml
  - libffi
  # - unrar
  - wget
  - kubernetes-cli
  - helm
  - bash-completion
  - aws-iam-authenticator
  - tmux
  - heroku
  - hub
  - bash
  - tree
  - cowsay
  - coreutils
  - gpg
  - autoconf
  - wxwidgets
  - asciinema
  - automake
  - readline
  - libxslt
  - libtool
  - unixodbc
  - unzip
  - curl

casks:
  - fig
  # - docker
  - responsively
  - insomnia
  # - insomnia-designer
  - the-unarchiver
  # - zoom
  - cyberduck
  - evernote
  - virtualbox
  - vagrant
  - ngrok
  - gpg-suite
  - slack
  - discord
  - dropbox
  - google-cloud-sdk
  - font-fira-code
  - font-hack-nerd-font
  - jetbrains-toolbox
  - iterm2
  - sublime-text
  - visual-studio-code
  # - principle
  - sketch
  # - sketch-toolbox
  - sourcetree
  # - github-desktop
  - skyfonts
  # - balsamiq-mockups
  # - adobe-creative-cloud
  - dash
  # - lingo
  # - robo-3t
  # - sequel-pro
  # - pgadmin3
  - mysqlworkbench
  - postico
  # - keycastr
  - 1password
  # - gitter
  # - hipchat
  # - skype
  # - steam
  # - tunnelbear
  # - spectacle
  # - utorrent
  # - divvy
  - obs
  - paw
  # - flux
  - screenflow
  - firefox
  - google-chrome
  # - google-chrome-canary
  # - firefoxnightly
  # - webkit-nightly
  # - chromium
  # - torbrowser
  # - radio-silence
  - loopback
  - graphql-playground
  - postman
  - signal
  - telegram
