directories:
  - "{{ user_home_directory }}/Developer"
  - "{{ user_home_directory }}/Developer/GoLang"
  - "{{ user_home_directory }}/Developer/Trashcan"
  - "{{ user_home_directory }}/Developer/OpenSource"
  - "{{ user_home_directory }}/Developer/github.com/straw-hat-team"
  - "{{ user_home_directory }}/Developer/github.com/yordis"
  - "{{ user_home_directory }}/Developer/gitlab.com/straw-hat-team"
  - "{{ user_home_directory }}/Developer/docker-desktop/kubernetes/local-storage-sc"
