directories:
  - "{{ user_home_directory }}/Developer"
  - "{{ user_home_directory }}/Developer/GoLang"
  - "{{ user_home_directory }}/Developer/Trashcan"
  - "{{ user_home_directory }}/Developer/OpenSource"
  - "{{ user_home_directory }}/Developer/github.com/straw-hat-team"
  - "{{ user_home_directory }}/Developer/github.com/yordis"
  - "{{ user_home_directory }}/Developer/gitlab.com/straw-hat-team"
  - "{{ user_home_directory }}/Developer/docker-desktop/kubernetes/local-storage-sc"

symlinks:
  - src: "default-npm-packages.symlink"
    dest: ".default-npm-packages"
  - src: "default-python-packages.symlink"
    dest: ".default-python-packages"
  - src: "default-gems.symlink"
    dest: ".default-gems.symlink"
  - src: "editorconfig.symlink"
    dest: ".editorconfig"
  - src: "emacs.symlink"
    dest: ".emacs"
