directories:
  - "{{ user_home_directory }}/Developer"
  - "{{ user_home_directory }}/Developer/GoLang"
  - "{{ user_home_directory }}/Developer/Trashcan"
  - "{{ user_home_directory }}/Developer/OpenSource"
  - "{{ user_home_directory }}/Developer/github.com/straw-hat-team"
  - "{{ user_home_directory }}/Developer/github.com/yordis"
  - "{{ user_home_directory }}/Developer/gitlab.com/straw-hat-team"

symlinks:
  - src: "zed/settings.json"
    dest: ".config/zed/settings.json"
  - src: "zed/keymap.json"
    dest: ".config/zed/keymap.json"
  - src: "default-npm-packages"
    dest: ".default-npm-packages"
  - src: "default-python-packages"
    dest: ".default-python-packages"
  - src: "default-gems"
    dest: ".default-gems"
  - src: "editorconfig"
    dest: ".editorconfig"
  - src: "emacs"
    dest: ".emacs"
  - src: "ssh/config"
    dest: ".ssh/config"
