version: "3.8"
services:
  superagi-backend:
    container_name: superagi-backend
    image: "superagidev/superagi:main"
    depends_on:
      - super__redis
      - super__postgres
    networks:
      - super_network
    env_file:
      - ./services/superagi/config.yaml
    command: ["/app/wait-for-it.sh", "super__postgres:5432","-t","60","--","/app/entrypoint.sh"]

  superagi-celery:
    container_name: superagi-celery
    image: "superagidev/superagi:main"
    env_file:
      - ./services/superagi/config.yaml
    command: ["/app/entrypoint_celery.sh"]
    volumes:
      - "./volumes/superagi-celery/workspace:/app/workspace"

  superagi-frontend:
    container_name: superagi-frontend
    image: "superagidev/superagi-frontend:main"
    environment:
      NEXT_PUBLIC_API_BASE_URL: /api
