plugins:
  - name: opentofu
    url: https://github.com/virtualroot/asdf-opentofu.git
  - name: elixir
    url: https://github.com/asdf-vm/asdf-elixir
  - name: erlang
    url: https://github.com/asdf-vm/asdf-erlang
  - name: golang
    url: https://github.com/kennyp/asdf-golang.git
  - name: deno
    url: https://github.com/asdf-community/asdf-deno.git
  - name: nodejs
    url: https://github.com/asdf-vm/asdf-nodejs
  - name: terragrunt
    url: https://github.com/lotia/asdf-terragrunt.git
  - name: terraform-docs
    url: https://github.com/looztra/asdf-terraform-docs
  - name: terraform
    url: https://github.com/Banno/asdf-hashicorp.git
  - name: python
    url: https://github.com/danhper/asdf-python
  - name: ruby
    url: https://github.com/asdf-vm/asdf-ruby

versions:
  - name: elixir
    version: 1.15.7
  - name: erlang
    version: 26.1.2
#    environment:
#      CFLAGS: "-O2 -g -fno-stack-check"
#      KERL_CONFIGURE_OPTIONS: "--disable-hipe --with-ssl={{ openssl_path.stdout }}"
  - name: golang
    version: 1.21.3
  - name: deno
    version: 1.37.2
  - name: nodejs
    version: 20.10.0
  - name: python
    version: 3.12.0
  - name: ruby
    version: 3.2.2

global_versions:
  - name: elixir
    version: 1.15.7
  - name: erlang
    version: 26.1.2
  - name: golang
    version: 1.21.3
  - name: deno
    version: 1.37.2
  - name: nodejs
    version: 18.18.2
  - name: python
    version: 3.12.0
  - name: ruby
    version: 3.2.2
